### ISSUE TITLE
AttributeError: 'InstagramAPI' object has no attribute 'username_id'

### ISSUE THREAD

**Issue by easysports** [rjruizfdez/insta-unfollow#56]
## Expected vs Actual Behavior
I have double checked the Username and Password, they are correct
I am trying to run the following command python main.py -u USER -p PASSWORD -o info
My password has no symbols, and two numbers
Just to be sure, do I need to use quotes "" for the USER and password? Do I need to use an "@" for the username?
I have tried all combinations and had no luck.
I keep getting the following error

Login not successful
Traceback (most recent call last):
  File "main.py", line 187, in <module>
    main()
  File "main.py", line 143, in main
    for i in api.getTotalSelfFollowers():
  File "C:\Users\12512\Desktop\GolfCarts\Insta3\LevPasha\InstagramAPI.py", line 162, in getTotalSelfFollowers
    return self.getTotalFollowers(self.username_id)
AttributeError: 'InstagramAPI' object has no attribute 'username_id'

Any help would be appreciated, Thanks

## Specifications

 - Operative system:
Windows
 - Version (e.g. Python version):

Python 3.8.10

**Comment by john-szetho** [comment]
I am also having this problem. Any solutions yet?

```
Login not successful
Traceback (most recent call last):
  File "~/instagram-followers-bot/main.py", line 187, in <module>
    main()
  File "~/instagram-followers-bot/main.py", line 143, in main
    for i in api.getTotalSelfFollowers():
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/instagram-followers-bot/LevPasha/InstagramAPI.py", line 162, in getTotalSelfFollowers
    return self.getTotalFollowers(self.username_id)
                                  ^^^^^^^^^^^^^^^^
AttributeError: 'InstagramAPI' object has no attribute 'username_id'. Did you mean: 'username'?
```

**Comment by sahilbansalweb** [comment]
got same type of error
